actions

diff --git a/.github/workflows/07-status.yaml b/.github/workflows/07-status.yaml
--- a/.github/workflows/07-status.yaml
+++ b/.github/workflows/07-status.yaml
@@ -10,4 +10,11 @@ jobs:
       - name: Run Build 
         run: |
           echo "Running Build..."
-          exit 1    # Simulate a build failure
+          exit 1    # Simulate a build failure 
+
+      
+      #-------------------------------
+      # POST SELECTION (Jenkins Style)
+      #-------------------------------
+
+      
